name: talenty_common
description: Flutter shared package for Talenty
version: 0.0.1

environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  beamer: ^1.5.3
  flutter_markdown: ^0.6.13
  intl: ^0.17.0
  responsive_builder: ^0.4.3
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter: